    - &<org.name>
        Name: <org.name>
        ID: <org.mspid>
        MSPDir: <org.msp.dir>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('<org.mspid>.admin', '<org.mspid>.peer', '<org.mspid>.client')"
            Writers:
                Type: Signature
                Rule: "OR('<org.mspid>.admin', '<org.mspid>.client')"
            Admins:
                Type: Signature
                Rule: "OR('<org.mspid>.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('<org.mspid>.peer')"
        AnchorPeers:
