    - &<org.name>
        Name: <org.name>
        ID: <org.mspid>
        MSPDir: <org.msp.dir>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('<org.mspid>.member')"
            Writers:
                Type: Signature
                Rule: "OR('<org.mspid>.member')"
            Admins:
                Type: Signature
                Rule: "OR('<org.mspid>.admin')"
